name: tidy
description: A completionist set of lint rules, aligned with Dart SDK versions.
version: 3.11.0
repository: https://github.com/mockturtl/tidy

topics:
  - lints

environment:
  sdk: '>=3.11.0 <4.0.0'
